# Generated by Django 4.1.1 on 2022-10-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mc_donalds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stuff',
        ),
    ]
